spring.application.name=merchant-intelligence

# PostgreSQL
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/merchant_intelligence}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# Server
server.port=${PORT:8080}